# Generated by Django 3.1 on 2020-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
