# Generated by Django 3.1 on 2020-08-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_export_csv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='file',
        ),
    ]
