# Generated by Django 3.1 on 2020-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_export_csv', '0002_remove_students_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms_Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('age', models.IntegerField(default=0)),
                ('birth_date', models.DateField()),
                ('list_one', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50)),
                ('list_two', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50)),
            ],
        ),
    ]
