# Generated by Django 3.1 on 2020-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_export_csv', '0003_forms_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms_example',
            name='list_one',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forms_example',
            name='list_two',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50, null=True),
        ),
    ]
